mindmap
RICE
  CLI tools
    Languages
      Scripting
        Lua
          lua 5.1
          luajit
          luarocks
          lua_ls
        Python
        Fennel
      For fun
        Pascal
          fpc
        OCaml
          dune
      Odin
        odin
        ols
      C
        gcc
        clang
      JVM
        Scala
          scalac
          sbt
          giter8
          coursier
        OpenJDK
      Other
        LaTex
          tectonic
        Mermaid
    Development enviroment
      neovim
      lazygit
      Midnight Commander
    shell
      fish
      bash
  Desktop enviroment
    wezterm
    sway
      swaybar
      wlroots
      sway
    rofi
    pipewire
    proprietary codecs
  GUI applications
    flatpak
      Steam
    Ardour
    Mozzila Firefox
  Other
    fonts
    backgrounds
    documentation