mindmap
((RICE))
  (DONE)
    {{Languages}}
      Lua 
      Fennel
      Python
      Scala
      Pascal
      C
      Odin
      Java
      JS
      OCaml
      Go
    {{Tools}}
      Mermaid
      Latex
    {{Devenv}}
      Lazygit
      Midnight Commander
    {{Desktop}}
      Wezterm
  (PENDING)
    {{Languages}}
    {{Tools}}
    {{Devenv}}
      Nvim
        Refactoring and<br/>lsp specific stuff
          DSLs
            autotools_ls
            web
              html
              htmx
              jsonls
              sqlls
            taplo
            yamlls
          Programming
            For fun projects
              ocamllsp
              ols
              GPU SLs
                glsl_analyzer
                wgsl_analyzer
            scripting
              bashls  
              fennel_ls
              lua_ls
              pyright
            c stuff
              asm_lsp  
              clangd
            Occasionally needed
              gopls
              jdtls
              tsserver
          Docs
            marksman  
            texlab
        Theme
    {{Desktop}}
      fonts
    {{GUI applications}}
      Firefox
      Multimedia
        mpv
        imv
        zathura
      flatpak
        Pixolarama
        Xournal++
        Gimp
    {{Other}}  
      wallpapers
      documentation
  (NEED TO DO IN WM)
    {{Desktop}}
      sway
        swaybar
        wlroots
        sway
      rofi
      pipewire
      proprietary codecs
    {{GUI applications}}
      flatpak
        Steam
      Ardour
        Carla
        Cardinal
    {{Languages}}
    {{Tools}}
    {{Devenv}}
