%%{init: {'flowchart' : {'curve' : 'linear'}}}%%

graph TD

bash 
fish
utils
ssh
buildtools

c
fennel
go
java 
js 
lua 
ocaml 
odin 
pascal 
python 
scala

latex
lazygit
mermaid
nvim

fonts
i3wm
sway
wallpapers
wezterm

flatpak
gdbgui
multimedia

browser

bash --> utils
fish --> utils

bash --> ssh
fish --> ssh
utils --> ssh

c --> buildtools
go --> buildtools
python --> buildtools

lua --> fennel
c --> lua

bash --> ocaml
fish --> ocaml

bash --> odin
fish --> odin
c --> odin

java --> scala
utils --> scala

js --> mermaid

utils --> latex

utils --> lazygit
ssh --> lazygit

lua --> nvim
fennel --> nvim
buildtools --> nvim
utils --> nvim

utils --> fonts
python --> fonts

utils --> i3wm
bash --> i3wm
fish --> i3wm
wezterm --> i3wm
fonts --> i3wm
wallpapers --> i3wm

utils --> sway
bash --> sway
fish --> sway
wezterm --> sway
fonts --> sway
wallpapers --> sway

utils --> wallpapers

fonts --> wezterm
fish --> wezterm
bash --> wezterm

browser --> gdbgui
python --> gdbgui
c --> gdbgui
